### ISSUE TITLE
Additive positional encoding?

### ISSUE THREAD

**Issue by YimengZhu** [quanpn90/NMTGMinor#16]
Hi Quan,

I read the paper "Very Deep Self-Attention Networks for End-to-End Speech Recognition
" and found the repo here. As stated on paper section 2.3, "While directly adding acoustic features to the positional encoding is harmful, potentially leading to divergence during training [6], we resolved that problem by simply projecting the concatenated features to a higher dimension before adding (512, as other hidden layers in the model)."

I didn't understand this point very well so I came here and try to find out how you implement it. However, if I understand your code correctly, this is indeed an additive positional encoding, correct? 
https://github.com/quanpn90/NMTGMinor/blob/213bc361ec1b78c4a7433dac69304af594f40f85/onmt/models/transformer_layers.py#L357

If I want to implement the concatenate of positional encoding, should this line become 
`out = torch.cat(word_emb, self.pos_emb[:len_seq, :].type_as(word_emb)), 2)`
?

Thanks in advance.

**Comment by quanpn90** [comment]
Hi,

Yes that is a pretty rough implementation of the position encoding. The word_emb however refers to the word embeddings in Machine Translation. For the context of speech recognition, I use a torch.nn.Linear function to map the features from (40 x 4 (for example) to 512) before adding with the pos_emb.

You can also concatenate like that too, yes.

Best regards,
Quan

**Comment by YimengZhu** [comment]
Thanks for the kind reply.
